server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=sharan
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=MySuperSecretKeyForJWT1234567890
